/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUITest;

/**
 *
 * @author Arquinsiel
 */
public class Client_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Client_GUI
     */
    public Client_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ContactList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : ((javax.persistence.Query)null).getResultList();
        label1 = new java.awt.Label();
        StatusPanel = new javax.swing.JPanel();
        StatusLabel = new javax.swing.JLabel();
        ContactsPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        AccountMenu = new javax.swing.JMenu();
        AddAccountMenuItem = new javax.swing.JMenuItem();
        RemoveAccountMenuItem = new javax.swing.JMenuItem();
        ContactsMenu = new javax.swing.JMenu();
        AddContactMenuItem = new javax.swing.JMenuItem();
        StartChatMenuItem = new javax.swing.JMenuItem();
        ToolsMenu = new javax.swing.JMenu();
        PreferencesMenuItem = new javax.swing.JMenuItem();
        HelpMenu = new javax.swing.JMenu();
        AboutBoxMenuItem = new javax.swing.JMenuItem();
        OnlineHelpMenuItem = new javax.swing.JMenuItem();

        label1.setText("label1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        StatusPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Connection Status"));

        StatusLabel.setText("Connection Status Goes Here");

        javax.swing.GroupLayout StatusPanelLayout = new javax.swing.GroupLayout(StatusPanel);
        StatusPanel.setLayout(StatusPanelLayout);
        StatusPanelLayout.setHorizontalGroup(
            StatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(StatusLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        StatusPanelLayout.setVerticalGroup(
            StatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatusPanelLayout.createSequentialGroup()
                .addComponent(StatusLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ContactsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Contacts"));

        javax.swing.GroupLayout ContactsPanelLayout = new javax.swing.GroupLayout(ContactsPanel);
        ContactsPanel.setLayout(ContactsPanelLayout);
        ContactsPanelLayout.setHorizontalGroup(
            ContactsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );
        ContactsPanelLayout.setVerticalGroup(
            ContactsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
        );

        AccountMenu.setText("Account");

        AddAccountMenuItem.setText("Add Account");
        AddAccountMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddAccountMenuItemActionPerformed(evt);
            }
        });
        AccountMenu.add(AddAccountMenuItem);

        RemoveAccountMenuItem.setText("Remove Account");
        AccountMenu.add(RemoveAccountMenuItem);

        jMenuBar1.add(AccountMenu);

        ContactsMenu.setText("Contacts");

        AddContactMenuItem.setText("Add Contact");
        AddContactMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddContactMenuItemActionPerformed(evt);
            }
        });
        ContactsMenu.add(AddContactMenuItem);

        StartChatMenuItem.setText("Start New Chat");
        ContactsMenu.add(StartChatMenuItem);

        jMenuBar1.add(ContactsMenu);

        ToolsMenu.setText("Tools");

        PreferencesMenuItem.setText("Preferences");
        ToolsMenu.add(PreferencesMenuItem);

        jMenuBar1.add(ToolsMenu);

        HelpMenu.setText("Help");
        HelpMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpMenuActionPerformed(evt);
            }
        });

        AboutBoxMenuItem.setText("About");
        AboutBoxMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AboutBoxMenuItemMouseClicked(evt);
            }
        });
        AboutBoxMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutBoxMenuItemActionPerformed(evt);
            }
        });
        HelpMenu.add(AboutBoxMenuItem);

        OnlineHelpMenuItem.setText("Online Help");
        HelpMenu.add(OnlineHelpMenuItem);

        jMenuBar1.add(HelpMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StatusPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ContactsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ContactsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StatusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddAccountMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddAccountMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddAccountMenuItemActionPerformed

    private void AboutBoxMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutBoxMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AboutBoxMenuItemActionPerformed

    private void AddContactMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddContactMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddContactMenuItemActionPerformed

    private void HelpMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpMenuActionPerformed
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog(null, "This is where text goes.");
    }//GEN-LAST:event_HelpMenuActionPerformed

    private void AboutBoxMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutBoxMenuItemMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AboutBoxMenuItemMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Client_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AboutBoxMenuItem;
    private javax.swing.JMenu AccountMenu;
    private javax.swing.JMenuItem AddAccountMenuItem;
    private javax.swing.JMenuItem AddContactMenuItem;
    private java.util.List ContactList;
    private javax.swing.JMenu ContactsMenu;
    private javax.swing.JPanel ContactsPanel;
    private javax.swing.JMenu HelpMenu;
    private javax.swing.JMenuItem OnlineHelpMenuItem;
    private javax.swing.JMenuItem PreferencesMenuItem;
    private javax.swing.JMenuItem RemoveAccountMenuItem;
    private javax.swing.JMenuItem StartChatMenuItem;
    private javax.swing.JLabel StatusLabel;
    private javax.swing.JPanel StatusPanel;
    private javax.swing.JMenu ToolsMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
